import type { Config } from 'tailwindcss';
const config: Config = {
    content: [
        './pages/**/*.{js,ts,jsx,tsx,mdx}',
        './components/**/*.{js,ts,jsx,tsx,mdx}',
    ],
    theme: {
        extend: {
            colors: {
                deloitteSidebar: '#020920',
                sidebarSelectedBlue: '#4112FF',
                deloitteFooter: '#0C173A',
                deloitteCopyright: '#7F8FA8',
                deloitteGreen: '#86BC25',
                greylight: '#8a8a8a',
                lightPurple: '#E1D9FF',
                borderFocus: '#4112FF',
                primary_300: '#6741FF',
                primary_400: '#3C12ED',
                n_neutral_600: '#677397',
                n_neutral_800: '#35426F',
                n_neutral_100: '#FFFFFF',
                n_neutral_125: '#FAFBFC',
                n_neutral_150: '#F5F7FA',
                n_neutral_175: '#F0F3F7',
                n_neutral_200: '#E6EBF2',
                ne_neutral_300: '#BDC7D8',
                n_neutral_400: '#9FADC1',
                n_neutral_500: '#7F8FA8',
                n_neutral_700: '#647096',
                n_neutral_900: '#0C173A',
                n_neutral_1000: '#020920',
                mediumGrey: '#5F6A8F',
                lightGrey: '#D9DDE3',
                lightGreen: '#D6F1E3',
                darkGreen: '#0D7752',
                error: '#FFBF00',
                lightYellow: '#FFF3D9',
                pisa_blue_100: '#E1D9FF',
                pisa_blue_400: '#4112FF',
                pisa_blue_500: '#3C12ED',
                outlineFocus: '#0D69D4',
                danger: '#D00F32',
                bgDanger: '#FDE2E3',
                inactive: '#CBD0DA66',
                red_re_10040: '#fad0d766',
                yellow_ye_100: '#ffebc0',
                yellow_yb_400: '#FFB114',
                neutral_n_200: '#CBD0DA',
                red_rb_400: '#E71138',
                red_r_50: '#B00020',
                errorRed: '#E02424',
                n_neutral_200_40: '#F8FAFC',
                border_neutral_regular: '#E5EAF1',
                primary_p_e_200: '#8D71FF',
            },
            maxWidth: {
                sixty: '60px',
                fivefifty: '550px',
                fiveHundred: '500px',
                sidebarCollapsed: '88px',
                sidebarExpanded: '256px',
            },
            maxHeight: {
                sixtyVh: '60vh',
            },
            fontFamily: {
                inter: ['Inter'],
                olympicHeadline: ['Olympic-Headline', 'normal'],
            },
            letterSpacing: {
                text: '0.002em',
                twentyFour: '0.024px',
                thirtyTwo: '0.032px',
            },
            fontSize: {
                ten: '0.625rem',
                twelve: '0.75rem',
                thirteen: '0.8125rem',
                fourteen: '0.875rem',
                eighteen: '1.125rem',
                twenty: '1.25rem',
                twentyTwo: '1.375rem',
                twentySix: '1.625rem',
                thirty: '1.875rem',
                sixty: '3.75rem',
            },
            lineHeight: {
                sixteen: '1rem',
                eighteen: '1.125rem',
                twenty: '1.25rem',
                twentytwo: '1.375rem',
                twentyFour: '1.5rem',
                twentySix: '1.625rem',
                thirtyFour: '2.125rem',
                thirtySix: '2.25rem',
            },
            spacing: {
                two: '2px',
                six: '6px',
                thirteen: '13px',
                threeTwenty: '20rem',
                threeTwentyOne: '20.061rem',
                sixtyNine: '69px',
            },
            width: {
                sideDrawer: '375px',
                auditLogDetailsDrawer: '400px',
                auditLogDetailsDrawerWide: '800px',
                sixty: '60px',
            },
            borderWidth: {
                five: '5px',
            },
            minWidth: {
                sidebarExpanded: '256px',
                sidebarCollapsed: '88px',
                thirtyTwo: '2rem',
                sevenHalf: '7.5rem',
            },
            minHeight: {
                fifteen: '15rem',
                thirtyVh: '30vh',
                twentyFiveVh: '25vh',
                fiveVh: '5vh',
                tenVh: '10vh',
                screenMinusOneTwentyEightPx: 'calc(100vh - 128px)',
            },
            height: {
                twentySixPX: '6.5rem',
                onefiftyPX: '150px',
            },
            boxShadow: {
                shadow_100: '0 16px 32px 1px rgba(53, 66, 111, 0.03)',
            },
            padding: {
                twelve: '12rem',
            },
        },
    },
};
export default config;
