


try { fetch('http://127.0.0.1:7864/ingest/ab7286ab-46b1-4a39-81da-35546388e6d9', { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-Debug-Session-Id': '69016a' }, body: JSON.stringify({ sessionId: '69016a', location: 'layout.tsx:top-level', message: 'layout module evaluated on server', data: { reactAvailable: typeof require !== 'undefined' }, timestamp: Date.now(), hypothesisId: 'A,E', runId: 'post-fix' }) }).catch(() => { }); } catch (_) { }
// #endregion
import '@/styles/globals.scss';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { LayoutProvider } from "./LayoutProvider";
import Head from 'next/head';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;400;700&display=swap" rel="stylesheet" />
        <meta name="viewport" content="width=device-width" />
      </Head>
      <body
        style={{
          margin: 0,
          fontFamily: 'Inter, sans-serif',
          overflowY: 'hidden',
          position: 'fixed',
          top: 0,
          height: '100%',
          width: '100%',
        }}
      >
        <LayoutProvider>{children}</LayoutProvider>
      </body>
    </html>
  );
}
