


try { fetch('http://127.0.0.1:7864/ingest/ab7286ab-46b1-4a39-81da-35546388e6d9', { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-Debug-Session-Id': '69016a' }, body: JSON.stringify({ sessionId: '69016a', location: 'layout.tsx:top-level', message: 'layout module evaluated on server', data: { reactAvailable: typeof require !== 'undefined' }, timestamp: Date.now(), hypothesisId: 'A,E', runId: 'post-fix' }) }).catch(() => { }); } catch (_) { }
// #endregion
import '@/styles/globals.scss';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { LayoutProvider } from "./LayoutProvider";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LayoutProvider>{children}</LayoutProvider>
      </body>
    </html>
  );
}
